stages:
  - build
  - test

build:
  stage: build
  image: gcc:latest
  script:
    - apt-get autoclean
    - apt-get update && apt-get install -y cmake clang libcunit1-dev libcunit1-doc libcmocka-dev
    - cmake -S . -B build
    - cmake --build build
  artifacts:
    paths:
      - build/

test:
  stage: test
  image: gcc:latest
  script:
    - ./build/test_commands
    - ./build/test_hash_table
    - ./build/test_webserver
